### ISSUE TITLE
XML import- error message

### ISSUE THREAD

**Issue by PetyaKangalova** [younginnovations/aidstream#106]
I am supporting a publisher ([UNITAID](https://www.iatiregistry.org/publisher/utd)) in using the XML import feature. When importing the file I receive the following error-  **The uploaded file must be an Xml file** (see screenshot below). 
![image](https://user-images.githubusercontent.com/24607542/28162185-2403a20e-67be-11e7-8ff9-9457de18ec86.png)

The file I am uploading is an XML file and validates against the IATI schema- see results from IATI public validator in [here](http://validator.iatistandard.org/?perm=Unitaid_file_1499941170.xml).

Please note that the file is using version 1.01 of IATI, however, we have encountered the same error when testing the XML import with other IATI files as well.

Would you be able to look into this and let me know how we can proceed with importing the file?

**Comment by shresthaKiran** [comment]
Dear Petya,

Could you please send us the xml file.

**Comment by PetyaKangalova** [comment]
Hi Kiran,
I have sent the file to support@aidstream.org. Let me know if you received it.
Thanks

**Comment by shresthaKiran** [comment]
Hello Petya,

Thank you for sending the file. 

It seems the file is missing `<?xml` version="1.0" encoding="UTF-8"?>` tag due to which, it was not recognized as xml file. 

Currently, Aidstream only supports IATI xml version '1.03', '1.05' and onwards. To be able to import this xml, you have to change the IATI xml version to atleast '1.03' and also remove " <ir:registry-record xml:lang="en" file-id="utd-1" source-url="http://terrance.who.int/mediacentre/unitaid" publisher-id="utd" publisher-role="Funding" contact-email="unitaid@who.int" donor-id="utd" donor-type="40" title="UNITAID Activity Files" activity-period="2007-2016" last-updated-datetime="2016-09-30T00:00:00Z" generated-datetime="2016-12-20T00:00:00Z" verification-status="1" format="xml" license="IATI" />" tag from the xml file.

Please have a look into https://github.com/younginnovations/aidstream/wiki/How-do-I-import-activities-form-a-XML-file-%3F link to know about xml importer.

Best Regards,
Kiran

**Comment by PetyaKangalova** [comment]
Many thanks for looking into this so quickly @sachit-singh  I have now fixed the file but I am still getting an error with the XML  import. I will share the updated file via email. Would woul be able to look into this again?


![image](https://user-images.githubusercontent.com/24607542/28328580-ed3efffa-6bde-11e7-9915-e23450b22e39.png)


Best wishes,
Petya

**Comment by sachit-singh** [comment]
Hello Petya,

I just tried importing your xml file into my test account as well as yours. However I did not get this error. I'm a little confused. Except for the error for the missing type attribute for the Activity Identifier Element.

Could you please verify?

Thank you.

**Comment by PetyaKangalova** [comment]
Hi Sachit,

I tried again a few times and get the same error. Weirdly, the error message in red disappears after a few seconds, but the activities are not imported. I am using Firefox for my test account.

Would you be able to share a screenshot with the error you get? In a way this is good news as it means that the file has been uploaded successfully and UNITAID will then be able to upload their files if moved to version 1.03. I will be speaking to the them next week so can ask them to test the upload as well and see what error they get in their account. 

Any other advice in the meantime will be much appreciated.

Many thanks,
Petya

**Comment by sachit-singh** [comment]
Hello Petya,

I'm a bit confused as well. I have attached the screenshot of the Activity that I uploaded from the UnitAid Xml file that you had sent me, into your test account (Petya_IATI_test account).

![petya_2](https://user-images.githubusercontent.com/8382151/28365174-35680736-6ca7-11e7-8a42-7b54140ff468.png)

**Comment by PetyaKangalova** [comment]
Hi Sachit,
Thanks again for the quick response. I am not sure why this is occurring. I have asked UNITAID to try importing the file in their account and see whether they get the same error. I will probably talk to them next week, so if it is okay, let's keep the issue open and I will provide an update once they have tested with their account next week.

Best,
Petya

**Comment by sachit-singh** [comment]
Hi Petya,

Could you try logging out and then logging in again and then importing the file and tell me if you have the same problem??

Thank you.

**Comment by PetyaKangalova** [comment]
Hi Sachit,
Yes, logging out and in worked and the file was imported successfully. Many thanks again! I will close the issue now.
Best,
Petya

**Comment by sachit-singh** [comment]
Hi Petya,

Not a problem :)

Best Regards,
Sachit
