### ISSUE TITLE
Invalid xml 

### ISSUE THREAD

**Issue by amy-silcock** [younginnovations/aidstream#137]
Hi,

Irise International's activity file is not valid xml.

We've had a look and notice that it contains illegal '&'s in the descriptions. This has been picked up by our pyIATI validation tests. Not sure if there are other errors.

Their data isn't been correctly pulled through to the IATI previewer and d-portal. 

Please could you take a look.

**Comment by rupakhetianjana** [comment]
Hello Amy,

Since we don't have data validators in the Aidstream, detection of error is not possible for the populated data. Rest, Aidstream published XML files contains standard aligned data which you are well aware.
 
Apologies for the late response for this ticket. 
But do we have a similar issue as I can see the corrected file published by Irise Internation's?

Thank you
Anjana

**Comment by amy-silcock** [comment]
Hi Anjana,

I'm not aware of a similar issue at the moment and I can't recreate the error. I suggest we close the issue and re-open if the issue re-occurs.

Thank you,

Amy
