### ISSUE TITLE
Org files not re-publishing with corrections

### ISSUE THREAD

**Issue by jahnvidave** [younginnovations/aidstream#141]
Hi Aidstream,

Two organisations (BRAC and Raleigh International) have been unable to re-publish their Organisation file, after having corrected their IATI Org ID in Aidstream.

Their Activity files re-publish to the IATI Registry with the correct identifier. But the Org file is still showing the wrong identifier.

When we try to re-publish the Org file, by clicking 'Publish Organisation to IATI', the message arises saying 'Organization data has been Published.' but the corrected file does not publish and the 'Published Date' does not change.

![image](https://user-images.githubusercontent.com/38503709/41035470-b0470c2e-6984-11e8-8364-84309f92626f.png)

Please can you look into why their corrected Org files are not publishing?

Thanks,
Jahnvi

**Comment by jahnvidave** [comment]
This has now arisen for a third organisation (INTERSOS Onlus).

**Comment by anjesh** [comment]
@jahnvidave currently when you update the reporting-org-identifier, it doesn't get reflected in the org-xml-file directly. You have to republish. One temporary way is to add a dummy element and delete that element and do the republishing. I tried with both BRAC and Raleigh International, and their correct identifiers are now showing in XML files. https://aidstream.org/files/xml/raleigh_int-org.xml https://aidstream.org/files/xml/brac_admin2-org.xml

I will create a new issue for a feature, that will allow user to change the state of the organisation to draft so that the user can go through the steps to publish organisation data without having to do the work-around. 

See if you are able to do the same for INTERSOS.

**Comment by jahnvidave** [comment]
Thank you Anjesh for your response and for republishing the org files for BRAC and Raleigh International.

I have now done the same for INTERSOS, which has worked.

That sounds like a brilliant idea, to have a feature that would allow users to change their organisation to draft, as we often face this issue of needing them to republish their file.

Thanks again.
Jahnvi
