### ISSUE TITLE
URGENT: Able To (Re)Publish Activity With Missing Data Migrated From V2.01

### ISSUE THREAD

**Issue by wendyrogers** [younginnovations/aidstream#21]
The publisher acord currently has a v2.01 file that fails validation (see http://dashboard.iatistandard.org/validation.html) because an activity 'GB-CHC-283302-GDRC08' has a document link that is missing the format attribute. The activity was still marked as 'Published' following migration to the new version of Aidstream. When I added another activity and re-published both activities in a single file the activity with the invalid document link was also incorrectly republished.

As part of the V2.01 migration activities that were missing mandatory elements were automatically put back into 'draft' mode as part of the migration process. Should we do this again so that all publishers with invalid data (and there are many as can be seen on the IATI dashboard at the above link) are required to mark their activities as verified, completed etc so that they are properly validated?

Alternatively, is there another way for ensuring that invalid data is not republished!

I think this is very important that we make sure that it is no longer possible to (re)publish in any way invalid data

**Comment by anjesh** [comment]
Wendy, I still see the problem here. Even if we move the published activities (with missing fields values) to draft, they will still be part of the big XML as long as they don't change that particular invalid activity. The overall XML will pull the published XML piece (the one they have already published) of that particular activity and add the updated one. The invalid activity will get only fixed, once they edit any field of that particular activity - in which case, the schema validation will catch those errors. 

One thing we can explore is to remove the invalid activity from the overall activity XML and then changing the status to draft. This might require a discussion and approval from the organisation as well. Thoughts?

**Comment by wendyrogers** [comment]
Thanks @anjesh and as was discussed with Bond we shall initially be contacting users (post upgrade) in order to get them to amend any activities which had previously been published but were still missing data.
