### ISSUE TITLE
Unable to upgrade from Lite to Core

### ISSUE THREAD

**Issue by jahnvidave** [younginnovations/aidstream#211]
Hi AidStream, 

Danmission are unable to move their AidStream account from Lite to Core. This is preventing them from including the data required by their donor.

When clicking on their profile picture, they do not get the option to move to Core:
![image](https://user-images.githubusercontent.com/38503709/50348456-b123e700-0530-11e9-8cc6-37d3b8f01498.png)

Please can you have a look into this, and help to upgrade their account to Core?

Thank you, Jahnvi

**Comment by manibibek** [comment]
Hi Jahnvidave, 

AidStream can be upgraded from Lite to Core from the Settings page.

<img width="484" alt="screen shot 2018-12-25 at 3 39 09 pm" src="https://user-images.githubusercontent.com/18477559/50419878-5a354f00-085b-11e9-8c80-76a9284bdc94.png">

Thank you

**Comment by PetyaKangalova** [comment]
@manibibek  Thanks, however, it seems that there is a bug. I can also switch back to Core but as you can see from Karen's screenshot above she does not have that option. I copied you in my last email to her. Could you look into this?
 

> Dear IATI.
> Thank you for your advice.
> I have now created another profile for Danmission in Core version.. But I cannot open it…. I used my own email xxx@danmission.dk and put a second email there xxx@danmission.dk [ you can see the specific emails on Zendesk].
> I guess that since my own email is also used in the Lite version – this is where I can open – the other does not open although I used another password (I intended to at least).
> Can you help me to delete the Lite version (and transfer the activity data if possible) so I can use the Core version?
> Thank you in advance,
> Best regards,
> Karen Helen

**Comment by rupakhetianjana** [comment]
@jahnvidave @PetyaKangalova 

To move AidStream account from Lite to Core, please find the help from image provided herewith. Since, normal user has only option to upgrade their organization through setting page instead of profile, below attached image has been taken from danmission's Organization setting page as a reference. 

- Click into the blue circle area `Upgrade AidStream` as shown in the picture to upgrade account. 

![setting](https://user-images.githubusercontent.com/42827731/50826695-790c0900-1364-11e9-96dd-2b4ca8656105.png)

By the help of this, Danmission can upgrade their account and can use the core version with intact data. In addition, we can help to delete the core version account which they have created recently.

**Comment by PetyaKangalova** [comment]
Thanks @Rupakheti ! Karen confirmed that she has managed to upgrade so closing this issue. Thanks again.
