### ISSUE TITLE
Unable To Tell Which Field Validation Error Relates To

### ISSUE THREAD

**Issue by wendyrogers** [younginnovations/aidstream#22]
When editing a long list of document links for activity for Camfed GB-CHC-1029161-CSCF551 I was getting an error 'Please select an item from the list' but was completely unable to tell which of the many fields the error related to?

**Comment by RajbanshiNeha** [comment]
In every form, after each label if you see an '*' it means that those fields are mandatory. All mandatory fields need to be filled before saving. In this case, the language field is required.

**Comment by wendyrogers** [comment]
Thanks for the update. However, I think that the majority of users will unfortunately not be aware of what is mandatory or not and will really need the field(s) in error being indicated much more specifically to them. This has unfortunately also been a problem for users with the V2.01 version of Aidstream .

**Comment by anjesh** [comment]
Right now, we are using frontend validation (using js) to catch and display those errors without having to sending the request to server. This makes the form filling a bit easy and quick. The current HTML5 based validation doesn't look proper, however we will explore the other good looking and user-friendly js-validation library. 

The server validation is intact for now - which we could use instead of the js validation.

**Comment by wendyrogers** [comment]
Thanks @anjesh and I think if you can do anything here to make it clear to the user which field is in error then that would be extremely welcome. When there is a form with lots of data it is extremely frustrating not to be able to tell which is the field that needs fixing

**Comment by sachit-singh** [comment]
This issue has been fixed already.
