### ISSUE TITLE
2.03 - Unable to delete planned disbursements

### ISSUE THREAD

**Issue by jahnvidave** [younginnovations/aidstream#230]
Hello,

On the 2.03 upgrade, it is not possible to delete planned disbursements that have been entered.

I can click the delete button to 'remove the block'. However, when I try to 'Save' these changes, I get the following message: 
![image](https://user-images.githubusercontent.com/38503709/51992359-c16ea080-24a4-11e9-943b-fc72e62b72dc.png)

If I click 'Cancel', it retains the planned disbursement (that I had deleted), it does not save the change that the entry was removed.

Please can you look into changing this so that it is possible to remove planned disbursements?

Many thanks,
Jahnvi

**Comment by rupakhetianjana** [comment]
Hello Janvi,

The top section of every element cannot be deleted in any versions. It can only be reset and new information can be entered. To delete the entire element block, Activity detail view page is there as shown below. 

![52547263-9eba8100-2dee-11e9-93f4-2bcca2b780e2 png 1366x768](https://user-images.githubusercontent.com/42827731/52547304-e4774980-2dee-11e9-9781-1f9402d73bc1.png)


 The save and cancel button will understand that you are trying to keep the element and hence information retains as per the changes made. Confusion might have occurred due to the icon present over there of a delete button. But for every top block, the delete button will work as a reset button.

Thank you!

**Comment by jahnvidave** [comment]
Hi @Rupakheti,

Thank you for your explanation and for pointing out how to delete an entire element block from the activity's overview page. That is really helpful.

Many thanks, Jahnvi
