### ISSUE TITLE
Open University unable to add Participating Organisations

### ISSUE THREAD

**Issue by jahnvidave** [younginnovations/aidstream#234]
Hi AidStream,

The Open University are trying to manually add participating organisations to their activities using the 'Use Organisation Finder' function on AidStream.

They fill out the information on the 'Organisation Finder' form, for the partner organisation and click 'Use this organisation'. However, the organisation does not appear on their list of partners and cannot be added to their activity.

I have been able to add participating organisations on their behalf.

Please can you investigate what is preventing them from manually adding participating orgs?

Many thanks,
Jahnvi

**Comment by manibibek** [comment]
HI, 

Some users are facing issues on Participating Organisations because of the browser(Internet Explorer) they are using. We are working to solve this issue and make it compatible with all browsers. 

You can follow up on the issue here https://github.com/younginnovations/aidstream/issues/194

Thank you
