### ISSUE TITLE
Has AidStream had it's hostname changed?

### ISSUE THREAD

**Issue by amy-silcock** [younginnovations/aidstream#310]
Hi,

Some AidStream files on the IATI Registry are throwing errors. e.g. 
![image](https://user-images.githubusercontent.com/27764077/66219797-b7e8a880-e6c3-11e9-89f9-9e3996d626fc.png)

The message is about hostname www.aidstream.org' not matching either of aidstream.org or np.aidstream.org. Do you have any knowledge of what might be happening?

Some organisations where this is happening:

https://www.iatiregistry.org/publisher/basicneeds
https://www.iatiregistry.org/publisher/ipa
https://www.iatiregistry.org/publisher/tbalert

**Comment by manibibek** [comment]
Hi Amy, 

On checking the individual organization's page, the URL of the individual Activity and Organization file is perfectly okay when I access those xml files from the URL on the browser. 

However, these issues were arising when IATI was trying to access the aidstream server with the domain www.aidstream.org instead of aidstream.org. We were not aware of this issue and we are working to fix this issue. Thank you for pointing it out. 

Regards, 
Mani

**Comment by amy-silcock** [comment]
Thanks Mani! We came to the same conclusion. 

We'll try and get a bulk fix done on the relevant AidStream files currently published to the IATI Registry. It would also be great to prevent the error from occurring again.

Best wishes,

Amy

**Comment by manibibek** [comment]
Hi Amy, 

We have fixed the issue from our end too and the hostname issue is only showing for one activity file for Basicneeds. Hopefully, it will also be updated once IATI refreshes the link.

Regards, 
Mani

**Comment by amy-silcock** [comment]
Thanks Mani!
