### ISSUE TITLE
XML generation error

### ISSUE THREAD

**Issue by DaveEade49** [younginnovations/aidstream#340]
The validator is encountering an error in XML throwing an incorrect standard version error - we have seen this before.

Here is the link to the validator report.

https://validator.iatistandard.org/report/hif-gh

**Comment by BibhaT** [comment]
While uploading an XML file, session was being used to enter the IATI Standard version. Incorrect IATI Standard version was being entered because the session data was not available al the moment hence it was going either empty or with the incorrect version. It was seemingly a momentary issue which has now been fixed. @DaveEade49
