### ISSUE TITLE
Improve Activities CSV Import Functionality

### ISSUE THREAD

**Issue by anjesh** [younginnovations/aidstream#45]
Current CSV import is very basic and the associated csv template is restricted to limited fields only. We plan to have multiple templates to deal with different use cases possible. There will be only one interface to upload the csv data in any template and the system will import these data into the system. The system flow will be the same and the current flow will be updated to include the intermediate step where the users will be able to decide which activities from the csv to import and which are to be ignored. The system will also allow to move forward even if some of the activity data have issues. 
1. User downloads one of the available templates
2. User fills the data in the template
3. User uploads the activity through the import interface
4. The system lists the activities and shows errors associated with any activity, alongside the activity. 
5. User decides which activity to import (checks the box for those valid activities only). The invalid activities (with any kind of error) can't be checked for the import.
6. User submits after the selection of the activities.
7. The system will import the selected activities.

The user will fix the problems with the data and again upload the same file. Those activities which are already imported will not able to be imported, with the message (Activity already exists in the system). 

TODO: We need to finalize the possible templates.

**Comment by pradhanrak** [comment]
The following are the mock-ups to show the steps to be carried out to import activities in bulk.
There basically three steps to carry out;
Step 1: This screen shows the Import Bulk Activities interface. In this page, different templates will be available for the users along with description for the templates. The users can download these templates and fill it with their organisation's data and import the CSV file from the same page. 
![step-1](https://cloud.githubusercontent.com/assets/8123056/15208107/8bfacbd2-1849-11e6-89a5-344f5100c358.png)

Step 2: This is an intermediate step in the activities importing process.
This following mockup shows the list of activities from the CSV file uploaded by the user. This list will show the following:
1. Activity Title
2. Activity Identifier
3. Error messages for the activities
![step-2-1](https://cloud.githubusercontent.com/assets/8123056/15208109/8e84f468-1849-11e6-8c4b-c0c94a211a65.png)
The system will not let users import activities which:
- are duplicates of existing activities. The title of the duplicate activity will be shown here.
- have errors. The errors will be shown for the users so that they can correct these error in the same file and upload it again.
  For these activities, the checkbox will the disabled.

If there are no errors in an activity, the users will be able to click on the checkbox for the activity. The user will see a message "No errors found." for these activities.
The following mockup shows an activity checked after which the 'Import' button is enabled. The users can click on this 'Import' button to import the error free activity/activities into the system.
![step-2-2](https://cloud.githubusercontent.com/assets/8123056/15208110/90a46666-1849-11e6-8f4b-c12269d6906c.png)
For the intermediate step, there will be a button that says 'Go back to Import Bulk Activities' to take back to that page so that they can upload the CSV file in which the errors has been corrected.

After the activities have been exported, the user is taken to the Activities list page with a message "One Activity Activity title has been imported."
![step-3](https://cloud.githubusercontent.com/assets/8123056/15208115/94220a28-1849-11e6-9d5a-30617ae4f914.png)

In this process activities can be imported to AidStream from a CSV file.
