### ISSUE TITLE
Option to delete unlinked XML files in AidStream

### ISSUE THREAD

**Issue by anjesh** [younginnovations/aidstream#7]
See https://github.com/younginnovations/aidstream-new/issues/6 for the background.

When the XML files are not linked with Registry, the user should see the delete option in the files listing in AidStream. The user should be able to delete the file.

**Comment by jacqkodden** [comment]
We have the same problem: first, we had 'unsegmented' mentioned in Aidstream and IATI registry, therefore having one general activity XML file only. However, later on it turned out that we should have put it at 'segmented', having country activity files now. But, the general file XML was put at published in Aidstream, although we did not register this in IATI (making a link to that general XML file). However, we are unable to delete that XML file in Aidstream now. It does not show in My Datasets (so that is OK, I guess), but I would like to delete that file in Aidstream too. How to do that?

**Comment by sachit-singh** [comment]
This feature has already been implemented into AidStream.
