### ISSUE TITLE
Question on branches

### ISSUE THREAD

**Issue by siemvaessen** [younginnovations/aidstream#74]
Hi there,

I just noticed Aidstream has +500 branches. (https://github.com/younginnovations/aidstream/branches) 

Is there a specific reason to have that many?

Thanks, Siem

**Comment by siemvaessen** [comment]
@anjesh bump.

**Comment by anjesh** [comment]
@siemvaessen apologies for the long silence. you are right about the branches, the number is high, which people don't have to know. They are our part of the internal gitflows and we have mirrored our internal repo with github and hence you are seeing them. We are planning to enable mirror for the master branch only, rather than entire repo. Thanks for noticing :)
