### ISSUE TITLE
SSL certificate chain is incomplete

### ISSUE THREAD

**Issue by andylolz** [younginnovations/aidstream#93]
See:
https://www.ssllabs.com/ssltest/analyze.html?d=https://aidstream.org

I think this is causing errors on the IATI registry e.g.:
https://iatiregistry.org/dataset/foei-998

…but also the IATI datastore e.g.:
http://datastore.iatistandard.org/api/1/error/dataset/foei-998

**Comment by hayfield** [comment]
http://serverfault.com/a/676078 indicates that there is likely a problem caused by requiring an 'Extra download' within both Certification Paths. While browsers are able to deal with this, because magic, the scripts behind the Registry and Datastore cannot.

https://github.com/zakjan/cert-chain-resolver#background provides further information on this, as well as a solution on how to solve it.

**Comment by HermanvanLoon** [comment]
Unfortunately this affects all publishers using Aidstream. No valid URL's can be automatically retrieved from the registry anymore.

**Comment by sachit-singh** [comment]
We have updated the SSL certificate for aidstream.org and also have tested from our end. It should be working now. Please re-open this issue if you find any further problems.

**Comment by andylolz** [comment]
Looks good to me!

**Comment by HermanvanLoon** [comment]
Thanks!

**Comment by sachit-singh** [comment]
You're welcome. And we're sorry for the inconvenience.
